### ISSUE TITLE
[CRASH] Cant Run Vulkan Because LWJGL Error

### ISSUE THREAD

**Issue by Sardine-G** [xCollateral/VulkanMod#332] opened 2023-12-02 07:26 UTC
the game only run for split scond (Only showing black) 
then crashes
the error it gave out seems related to lwjgl vulkan 

Here's the mc log: [latest.log](https://github.com/xCollateral/VulkanMod/files/13533685/latest.log)
Here's the crash log: [crash-2023-12-02_14.15.14-client.txt](https://github.com/xCollateral/VulkanMod/files/13533675/crash-2023-12-02_14.15.14-client.txt)

Running Cracked MultiMc (UltimMC) On Linux
Fedora 39 Onyx

**Comment by UltraBlackLinux** [comment] 2023-12-09 17:43
For the people who can't be bothered to download a log:
```
ava.lang.NoClassDefFoundError: org/lwjgl/vulkan/VkInstance
	at org.lwjgl.glfw.GLFWVulkan.glfwCreateWindowSurface(GLFWVulkan.java:332)
	at net.vulkanmod.vulkan.Vulkan.createSurface(Vulkan.java:311)
	at net.vulkanmod.vulkan.Vulkan.initVulkan(Vulkan.java:137)
	at net.vulkanmod.vulkan.VRenderSystem.initRenderer(VRenderSystem.java:58)
	at com.mojang.blaze3d.systems.RenderSystem.initRenderer(RenderSystem.java:1516)
	at net.minecraft.class_310.<init>(class_310.java:505)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
```
I can reproduce this on Prismlauncher, Arch Linux

**Comment by MCTVVTCM** [comment] 2024-01-20 13:15
do you start feature like use system glfw,maybe it effect your launching

**Comment by xCollateral** [comment] 2024-09-16 10:21
Quilt has some issues with library loading. I'll close this since it's a duplicate of #204

**Closed as completed by xCollateral** 2024-09-16 10:21 UTC
