### ISSUE TITLE
All blocks disappear when you fall below Y 0

### ISSUE THREAD

**Issue by andreasdc** [xCollateral/VulkanMod#156] opened 2022-12-15 23:29 UTC
As in the title, version 1.18.2, VulkanMod_1.18.2-0.2.0.jar from 14.12.2022

**Comment by saboooor** [comment] 2022-12-16 04:19
Just tested it on 1.19.3 and it actually happens when you fall into the void, below the minimum set Y value

**Comment by saboooor** [comment] 2022-12-16 04:25
looks like it happens in basically any unloaded area

**Comment by ezamelczyk** [comment] 2023-02-23 11:34
Can confirm it happens in unloaded areas but I haven't been able to reproduce it in the nether or the end. Seems to only affect overworld.

**Comment by ezamelczyk** [comment] 2023-02-23 12:03
Very simple steps to reproduce:

1. Make a hole all the way down to -60
2. Enter and exit the nether
3. Go down the hole. Rendering should break at y=0

**Comment by ezamelczyk** [comment] 2023-02-23 13:08
Issue doesn't exist on branch 1.18.2 so most likely regression

**Comment by andreasdc** [comment] 2023-02-23 16:19
Yes it started to happen after one of the newest updates.

**Comment by xCollateral** [comment] 2023-03-23 15:14
It should be fixed.

**Closed as completed by xCollateral** 2023-03-23 15:14 UTC
Labels: bug
