### ISSUE TITLE
Blocks (and non-blocks) not breaking

### ISSUE THREAD

**Issue by thasave14** [xCollateral/VulkanMod#403] opened 2024-04-08 19:31 UTC
I'm on this minecraft world with my friends on telegram (ignore their voices, it's italian) and there's this bug. All my specs and info are on the vids.

https://github.com/xCollateral/VulkanMod/assets/93542339/c2642b74-7780-41bc-bd29-efb99309d8f5
https://github.com/xCollateral/VulkanMod/assets/93542339/7cbb39d1-277e-4fce-acf5-2d55a65275df

**Comment by thasave14** [comment] 2024-04-08 19:39
oh and i found out that if i look to a non complete block i can see the blocks under it like x-ray. Same specs and everything

**Comment by Daxy7** [comment] 2024-04-19 16:39
https://github.com/xCollateral/VulkanMod/issues/402
same problem here with latest v4.0 1.20.4 on 1.20.4

**Comment by leominerxd** [comment] 2024-04-23 10:06
> the blocks under it like

mine issue a little different and have been fixed by removing ServerCore

**Comment by thasave14** [comment] 2024-04-24 13:24
yea but i dont have servercore

**Comment by Dashy22** [comment] 2024-04-28 01:38
I don't have server core this still happends exactly like the video

**Comment by Daxy7** [comment] 2024-04-29 09:02
https://github.com/xCollateral/VulkanMod/assets/91396482/0d26c511-805b-4d3d-baf9-89886cf7421d
I managed to fix it.
https://github.com/xCollateral/VulkanMod/assets/91396482/e806d59d-0625-4971-b4f9-c9c98f245bba
By disabling all optimizations and turning render/simulation distance to lowest.

**Comment by Daxy7** [comment] 2024-04-29 13:37
Edit: just changing chunk render to 2 fixed the issue. after re-putting to 12.

**Comment by xCollateral** [comment] 2024-04-29 15:11
Send logs and steps to reproduce, please.

**Comment by thasave14** [comment] 2024-04-29 19:00
the steps are easy i think, launch the mod, go on a random chunk, break blocks, for some reason it worked only on some chunks, and second, about the logs, i think i might have found something:

"[20:32:17] [Worker-Main-2/WARN]: Profile contained invalid signature for textures property (profile id: 93bf26d1-7a2d-3fbe-8354-01e4b39ab6e2)
[20:32:59] [Builder-0/ERROR]: Uncaught exception in thread "Builder-0"
java.lang.ArrayIndexOutOfBoundsException: Index 31 out of bounds for length 27
	at net.vulkanmod.render.chunk.build.RenderRegion.method_8314(RenderRegion.java:150) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at net.vulkanmod.render.chunk.build.light.data.LightDataAccess.compute(LightDataAccess.java:107) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at net.vulkanmod.render.chunk.build.light.data.ArrayLightDataCache.get(ArrayLightDataCache.java:71) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at net.vulkanmod.render.chunk.build.light.data.LightDataAccess.get(LightDataAccess.java:63) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at net.vulkanmod.render.chunk.build.light.data.LightDataAccess.get(LightDataAccess.java:69) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at net.vulkanmod.render.chunk.build.light.flat.FlatLightPipeline.getLightmap(FlatLightPipeline.java:61) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at net.vulkanmod.render.chunk.build.light.flat.FlatLightPipeline.calculate(FlatLightPipeline.java:37) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at net.vulkanmod.render.chunk.build.BlockRenderer.renderModelFace(BlockRenderer.java:110) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at net.vulkanmod.render.chunk.build.BlockRenderer.tessellateBlock(BlockRenderer.java:92) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at net.vulkanmod.render.chunk.build.BlockRenderer.renderBatched(BlockRenderer.java:71) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at net.vulkanmod.render.chunk.build.task.BuildTask.compile(BuildTask.java:138) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at net.vulkanmod.render.chunk.build.task.BuildTask.runTask(BuildTask.java:52) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at net.vulkanmod.render.chunk.build.TaskDispatcher.runTaskThread(TaskDispatcher.java:87) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at net.vulkanmod.render.chunk.build.TaskDispatcher.lambda$createThreads$0(TaskDispatcher.java:59) ~[VulkanMod_1.20.4-0.4.0.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]"

and if interested i found this too: "[20:30:01] [Render thread/INFO]: GLFW: 3.4.0 Win32 WGL Null EGL OSMesa VisualC DLL".

and of course the mod i used: "[20:29:24] [main/INFO]: Loading 123 mods:
	- badoptimizations 2.1.0
	- c2me 0.2.0+alpha.11.65
	   |-- c2me-base 0.2.0+alpha.11.65
	   |-- c2me-client-uncapvd 0.2.0+alpha.11.65
	   |-- c2me-fixes-chunkio-threading-issues 0.2.0+alpha.11.65
	   |-- c2me-fixes-general-threading-issues 0.2.0+alpha.11.65
	   |-- c2me-fixes-worldgen-threading-issues 0.2.0+alpha.11.65
	   |-- c2me-fixes-worldgen-vanilla-bugs 0.2.0+alpha.11.65
	   |-- c2me-notickvd 0.2.0+alpha.11.65
	   |-- c2me-opts-allocs 0.2.0+alpha.11.65
	   |-- c2me-opts-chunk-access 0.2.0+alpha.11.65
	   |-- c2me-opts-chunkio 0.2.0+alpha.11.65
	   |-- c2me-opts-math 0.2.0+alpha.11.65
	   |-- c2me-opts-scheduling 0.2.0+alpha.11.65
	   |-- c2me-opts-worldgen-general 0.2.0+alpha.11.65
	   |-- c2me-opts-worldgen-vanilla 0.2.0+alpha.11.65
	   |-- c2me-rewrites-chunk-serializer 0.2.0+alpha.11.65
	   |-- c2me-rewrites-chunkio 0.2.0+alpha.11.65
	   |-- c2me-server-utils 0.2.0+alpha.11.65
	   |-- c2me-threading-chunkio 0.2.0+alpha.11.65
	   |-- c2me-threading-lighting 0.2.0+alpha.11.65
	   |-- c2me-threading-worldgen 0.2.0+alpha.11.65
	   |-- com_electronwill_night-config_core 3.6.5
	   |-- com_electronwill_night-config_toml 3.6.5
	   |-- com_ibm_async_asyncutil 0.1.0
	   |-- net_objecthunter_exp4j 0.4.8
	   \-- org_threadly_threadly 7.0
	- centered-crosshair 1.0.6
	- clean-debug 0.4.4
	- experimentalperformance 0.1.1
	   |-- io_github_classgraph_classgraph 4.8.162
	   \-- org_openjdk_jol_jol-core 0.17
	- fabric-api 0.96.11+1.20.4
	   |-- fabric-api-base 0.4.36+78d798af4f
	   |-- fabric-api-lookup-api-v1 1.6.49+82b1bb3e4f
	   |-- fabric-biome-api-v1 13.0.16+78d798af4f
	   |-- fabric-block-api-v1 1.0.16+3e2216cb4f
	   |-- fabric-block-view-api-v2 1.0.4+78d798af4f
	   |-- fabric-blockrenderlayer-v1 1.1.46+78d798af4f
	   |-- fabric-client-tags-api-v1 1.1.7+78d798af4f
	   |-- fabric-command-api-v1 1.2.41+f71b366f4f
	   |-- fabric-command-api-v2 2.2.20+78d798af4f
	   |-- fabric-commands-v0 0.2.58+df3654b34f
	   |-- fabric-containers-v0 0.1.86+df3654b34f
	   |-- fabric-content-registries-v0 5.0.15+78d798af4f
	   |-- fabric-convention-tags-v1 1.5.10+78d798af4f
	   |-- fabric-crash-report-info-v1 0.2.23+78d798af4f
	   |-- fabric-data-attachment-api-v1 1.1.4+b90db5744f
	   |-- fabric-data-generation-api-v1 13.2.4+5c0133444f
	   |-- fabric-dimensions-v1 2.1.61+78d798af4f
	   |-- fabric-entity-events-v1 1.6.1+09fc25014f
	   |-- fabric-events-interaction-v0 0.7.1+389931eb4f
	   |-- fabric-events-lifecycle-v0 0.2.74+df3654b34f
	   |-- fabric-game-rule-api-v1 1.0.46+78d798af4f
	   |-- fabric-item-api-v1 2.2.0+d6f2b0844f
	   |-- fabric-item-group-api-v1 4.0.26+58f8c0124f
	   |-- fabric-key-binding-api-v1 1.0.41+78d798af4f
	   |-- fabric-keybindings-v0 0.2.39+df3654b34f
	   |-- fabric-lifecycle-events-v1 2.3.0+a67ffb5d4f
	   |-- fabric-loot-api-v2 2.1.9+78d798af4f
	   |-- fabric-message-api-v1 6.0.5+78d798af4f
	   |-- fabric-mining-level-api-v1 2.1.65+78d798af4f
	   |-- fabric-model-loading-api-v1 1.0.8+78d798af4f
	   |-- fabric-models-v0 0.4.7+9386d8a74f
	   |-- fabric-networking-api-v1 3.1.7+2e5ac5484f
	   |-- fabric-object-builder-api-v1 13.0.14+080016e44f
	   |-- fabric-particles-v1 1.1.7+78d798af4f
	   |-- fabric-recipe-api-v1 2.0.20+78d798af4f
	   |-- fabric-registry-sync-v0 4.0.19+58f8c0124f
	   |-- fabric-renderer-api-v1 3.2.4+78d798af4f
	   |-- fabric-renderer-indigo 1.5.4+78d798af4f
	   |-- fabric-renderer-registries-v1 3.2.53+df3654b34f
	   |-- fabric-rendering-data-attachment-v1 0.3.42+73761d2e4f
	   |-- fabric-rendering-fluids-v1 3.1.1+e761c6694f
	   |-- fabric-rendering-v0 1.1.56+df3654b34f
	   |-- fabric-rendering-v1 3.2.0+6fd945a04f
	   |-- fabric-resource-conditions-api-v1 2.3.14+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.20+df798a894f
	   |-- fabric-screen-api-v1 2.0.17+78d798af4f
	   |-- fabric-screen-handler-api-v1 1.3.55+78d798af4f
	   |-- fabric-sound-api-v1 1.0.17+78d798af4f
	   |-- fabric-transfer-api-v1 4.0.11+eb30349a4f
	   \-- fabric-transitive-access-wideners-v1 5.0.14+78d798af4f
	- fabricloader 0.15.7
	   \-- mixinextras 0.3.5
	- faster-random 3.0.3
	- fastipping 1.0.1
	- ferritecore 6.0.3
	- java 17
	- krypton 0.2.6
	   \-- com_velocitypowered_velocity-native 3.2.0-SNAPSHOT
	- ksyxis 1.2.2
	- lazy-language-loader 0.3.5
	- lazydfu 0.1.3
	- lithium 0.12.1
	- memoryleakfix 1.1.5
	- minecraft 1.20.4
	- modelfix 1.14
	- noframeratelimit 1.20.2+build.1
	- railoptimization 1.0
	- smoothscrollingrefurbished 1.1.2
	- stutterfix mc1.20.3-0.2.0
	- threadtweak 1.20.4-0.1.2
	- toomanyplayers 1.20.4-1.1.5
	   |-- libgui 9.2.2+1.20.2
	   |    |-- jankson 6.0.0+j1.2.3
	   |    |    \-- blue_endless_jankson 1.2.3
	   |    \-- libninepatch 1.2.0
	   \-- midnightlib 1.5.3
	- vulkanmod 0.4.0
	   |-- org_lwjgl_lwjgl-shaderc 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-linux 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-macos 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-macos-arm64 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-windows 3.3.2
	   |-- org_lwjgl_lwjgl-vma 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-linux 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-macos 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-macos-arm64 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-windows 3.3.2
	   |-- org_lwjgl_lwjgl-vulkan 3.3.2
	   |-- org_lwjgl_lwjgl-vulkan_natives-macos 3.3.2
	   \-- org_lwjgl_lwjgl-vulkan_natives-macos-arm64 3.3.2"

**Comment by xCollateral** [comment] 2024-05-01 16:10
I tried to reproduce it multiple times but could not manage to. Could you try if that happens without any other mod?

**Comment by thasave14** [comment] 2024-05-01 19:15
im gonna try

**Comment by thasave14** [comment] 2024-05-02 13:22
yea hum, i tried and it seems that without every other mod the issue gets fixed

**Comment by xCollateral** [comment] 2024-05-04 15:49
Finding which mods are causing the issue would be helpful.

**Comment by Daxy7** [comment] 2024-05-04 21:54
im running on java 17 version 1.20.4 and after 20-30 minutes of loading and changing chunks this happens seemingly at random. `VulkanMod_1.20.4-0.4.1`
Chunks do not render after a certain distance aswell.
using `/back` on the server causes the extreme visibleness of the bug as I replied previously using images.

Was running on a server using KingdomsX plugin and not much else directly related to chunks or rendering, nothing forge related.
https://github.com/xCollateral/VulkanMod/assets/91396482/f7f97980-9155-47d8-a8c2-80eacecdfedd

**Comment by thasave14** [comment] 2024-05-05 18:37
exactly the same, if previously i said that without mods it fixed, it was because i didn't run it long enough

**Comment by thasave14** [comment] 2024-05-05 19:21
and with 0.4.1 it still has the issue

**Comment by xCollateral** [comment] 2024-05-08 15:48
Could you check if the issue still occurs with the latest commit?

**Comment by thasave14** [comment] 2024-05-09 12:56
sure, ima do it

**Comment by Daxy7** [comment] 2024-05-09 16:01
@xCollateral Can you send a compiled development build of https://github.com/xCollateral/VulkanMod/commit/85e583d60f73020036ef45b6fea0226a0e0bcfd3 ?

**Comment by leominerxd** [comment] 2024-05-09 17:01
> @xCollateral Can you send a compiled development build of [85e583d](https://github.com/xCollateral/VulkanMod/commit/85e583d60f73020036ef45b6fea0226a0e0bcfd3) ?

https://github.com/xCollateral/VulkanMod/actions/runs/9004394464

**Comment by Daxy7** [comment] 2024-05-09 20:48
using what melamit suggested to install, the bug in action. seperate case. I did not check if the blocks updating bug was still an issue. It seems to be gone. will edit if occurs in rendering.
It is now chests/interactable blocks that dissapear after 20-30 minutes of gameplay.
https://github.com/xCollateral/VulkanMod/assets/91396482/ffb343c2-7e89-4a5c-9318-2bc6228e2a58

System specs:
https://github.com/xCollateral/VulkanMod/files/15267337/c602a195-f6d6-4e88-91c9-a94c76a6e9f7.txt

**Comment by leominerxd** [comment] 2024-05-10 11:58
> using what melamit suggested to install, the bug in action. seperate case. I did not check if the blocks updating bug was still an issue. It seems to be gone. will edit if occurs in rendering. It is now chests/interactable blocks that dissapear after 20-30 minutes of gameplay. https://github.com/xCollateral/VulkanMod/assets/91396482/ffb343c2-7e89-4a5c-9318-2bc6228e2a58
> 
> System specs: https://github.com/xCollateral/VulkanMod/files/15267337/c602a195-f6d6-4e88-91c9-a94c76a6e9f7.txt

I recommend not to use TLauncher, many reports that it is unsafe to use, don't have any proof but still, be careful with it. I recommend to use [ShatteredPrism](https://github.com/LunaisLazier/ShatteredPrism), you can check it's source code and unlike prismlauncher it supports FTB and Offline auth

**Comment by thasave14** [comment] 2024-05-12 18:13
i dont have so much freetime lately, can someone that has this issue check for me?

**Comment by Dashy22** [comment] 2024-05-14 03:17
i think it might depend on the device maybe or the mod itself, I just used the Vulkan mod solo and traveled out until after the spawn chunks and the blocks weren't disappearing after being broken or appearing after being placed.
And in the video the other guy showed, it was pretty laggy. And my device is also really bad.

**Comment by arturamiryan** [comment] 2024-05-16 18:38
I can confirm issue on the latest version. For me it's happens on a server and resolves with F3+A.

**Comment by xCollateral** [comment] 2024-06-10 14:40
dad55e7 should have solved this issue. Can someone check if it's still happening or not?

**Comment by arturamiryan** [comment] 2024-06-11 20:56
I will check. But it's hard, because I don't know how to reproduce the issue, other than just playing.
So, I just download artifact from here? https://github.com/xCollateral/VulkanMod/actions/runs/9419390665

**Comment by xCollateral** [comment] 2024-06-20 10:26
Latest version (0.4.3) should have solved this issue.

**Closed as completed by xCollateral** 2024-06-20 10:26 UTC

**Comment by lv37** [comment] 2024-06-20 19:34
Unfortunately, this is still an issue in 0.4.3
