### ISSUE TITLE
GLFW error 65548: Wayland: The platform does not support setting the input focus

### ISSUE THREAD

**Issue by topsyandpip56** [xCollateral/VulkanMod#344] opened 2023-12-15 17:25 UTC
Minecraft ver 1.20.1 with Fabric 0.15.0 launched via MultiMC with mod version 0.3.7. 

```
[19:22:38] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.15.0
[19:22:39] [main/INFO]: Loading 18 mods:
	- fabricloader 0.15.0
	   \-- mixinextras 0.3.0
	- java 17
	- minecraft 1.20.1
	- vulkanmod 0.3.7
	   |-- org_lwjgl_lwjgl-shaderc 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-linux 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-macos 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-macos-arm64 3.3.2
	   |-- org_lwjgl_lwjgl-shaderc_natives-windows 3.3.2
	   |-- org_lwjgl_lwjgl-vma 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-linux 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-macos 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-macos-arm64 3.3.2
	   |-- org_lwjgl_lwjgl-vma_natives-windows 3.3.2
	   |-- org_lwjgl_lwjgl-vulkan 3.3.2
	   |-- org_lwjgl_lwjgl-vulkan_natives-macos 3.3.2
	   \-- org_lwjgl_lwjgl-vulkan_natives-macos-arm64 3.3.2
[19:22:39] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/media/gnj/Minecraft/Linux/MultiMC/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[19:22:39] [main/INFO]: Compatibility level set to JAVA_17
[19:22:39] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.0).
[19:22:43] [Datafixer Bootstrap/INFO]: 188 Datafixer optimizations took 126 milliseconds
[19:22:45] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:22:45] [Render thread/INFO]: Setting user: topsyandpip56
[19:22:45] [Render thread/INFO]: == VulkanMod ==
[19:22:45] [Render thread/INFO]: Selecting Platform: WAYLAND
[19:22:45] [Render thread/INFO]: GLFW: 3.4.0 Wayland X11 GLX Null EGL OSMesa monotonic shared
[19:22:45] [Render thread/INFO]: Backend library: LWJGL version 3.3.1 SNAPSHOT
[19:22:50] [Render thread/WARN]: Failed to create window: 
net.minecraft.class_1041$class_4716: GLFW error 65548: Wayland: The platform does not support setting the input focus
	at net.minecraft.class_1041.method_4501(class_1041.java:196) ~[client-intermediary.jar:?]
	at org.lwjgl.glfw.GLFWErrorCallbackI.callback(GLFWErrorCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokePPPP(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.nglfwCreateWindow(GLFW.java:2024) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwCreateWindow(GLFW.java:2197) ~[lwjgl-glfw-3.3.1.jar:?]
	at net.minecraft.class_1041.<init>(class_1041.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_3682.method_16038(class_3682.java:21) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:486) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]

```

**Comment by thr3343** [comment] 2023-12-17 13:19
I don't have this issue when testing Wayland + Nvidia on my setup afaict
Is there a method of reproducing this?
As its possible I forgot to add a Wayland patch.

**Comment by Enn3Developer** [comment] 2024-01-07 22:18
Managed to reproduce the bug and the fix was to uncomment the line:
```java
GLFW.glfwWindowHint(GLFW_FOCUSED, GLFW_FALSE);
```
in `WindowMixin.java`

**Comment by zastrixarundell** [comment] 2024-01-08 15:12
Yep the issue is still happening on an integrated intel GPU (APU?) on `0.3.9` and with MC `1.20.4`. Running it with an `6600XT` I had no issue (and 2000+ FPS while being <50% GPU utilization), I'm probably going to see to build without the commented out code as per the comment above and check it out.

**Comment by thr3343** [comment] 2024-01-08 16:15
> Managed to reproduce the bug and the fix was to uncomment the line:
> 
> ```java
> GLFW.glfwWindowHint(GLFW_FOCUSED, GLFW_FALSE);
> ```
> 
> in `WindowMixin.java`

I'm completely unable to reproduce GLFW error 65548 on EndeavourOS
Afaik apparently this issue only occurs with Ubuntu
Is this actually the case? Or does it also occur with other distros?

**Comment by topsyandpip56** [comment] 2024-01-08 16:19
For me this error presented on Fedora KDE 39. 

> > Managed to reproduce the bug and the fix was to uncomment the line:
> > ```java
> > GLFW.glfwWindowHint(GLFW_FOCUSED, GLFW_FALSE);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in `WindowMixin.java`
> 
> I'm completely unable to reproduce GLFW error 65548 on EndeavourOS Afaik apparently this issue only occurs with Ubuntu Is this actually the case? Or does it also occur with other distros?

**Comment by topsyandpip56** [comment] 2024-01-08 16:20
> I don't have this issue when testing Wayland + Nvidia on my setup afaict Is there a method of reproducing this? As its possible I forgot to add a Wayland patch.

Sorry for delay, this was on an AMD Radeon RX Vega 64 with Fedora KDE 39. 
Using Mesa built from git (RADV).

**Comment by Enn3Developer** [comment] 2024-01-08 17:30
> Afaik apparently this issue only occurs with Ubuntu
Is this actually the case? Or does it also occur with other distros?

I'm using Solus KDE and I reproduced it

**Comment by Borketh** [comment] 2024-03-18 20:45
Reproduced, this is my current setup
```
OS: EndeavourOS Linux x86_64 
Host: GF63 Thin 11UC REV:1.0 
Kernel: 6.8.1-arch1-1 
Uptime: 38 mins 
Packages: 1745 (pacman) 
Shell: bash 5.2.26 
Resolution: 1920x1080 
DE: Plasma 6.0.2 
WM: kwin 
WM Theme: WillowDarkAltShader 
Theme: [Plasma], Adwaita-dark [GTK2/3] 
Icons: Gently-Color-Dark-Icons [Plasma], Gently-Color-Dark-Icons [GTK2/3] 
Terminal: konsole 
CPU: 11th Gen Intel i5-11400H (12) @ 4.500GHz [62.0°C] 
GPU: NVIDIA GeForce RTX 3050 Mobile 
GPU: Intel TigerLake-H GT1 [UHD Graphics] 
Memory: 5.28GiB / 31.06GiB (17%) 
```
Also using `prime-run` and `DRI_PRIME=1!`

**Comment by xCollateral** [comment] 2024-05-13 15:04
The issue should be fixed.

**Closed as completed by xCollateral** 2024-05-13 15:04 UTC
