### ISSUE TITLE
Minecraft crashing after statring single player

### ISSUE THREAD

**Issue by Kittyskj** [xCollateral/VulkanMod#283] opened 2023-08-19 14:28 UTC
No other mods

LOG:
---- Minecraft Crash Report ----
// My bad.

Time: 2023-08-19 17:26:38
Description: Unexpected error

java.lang.IllegalArgumentException: target is not GL_FRAMEBUFFER
	at net.vulkanmod.gl.GlFramebuffer.bindFramebuffer(GlFramebuffer.java:35)
	at com.mojang.blaze3d.platform.GlStateManager._glBindFramebuffer(GlStateManager.java:1079)
	at net.minecraft.class_276.method_29329(class_276.java:99)
	at net.minecraft.class_761.method_22710(class_761.java:1270)
	at net.minecraft.class_757.method_3188(class_757.java:1110)
	at net.minecraft.class_757.method_3192(class_757.java:880)
	at net.minecraft.class_310.method_1523(class_310.java:1219)
	at net.minecraft.class_310.method_1514(class_310.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.vulkanmod.gl.GlFramebuffer.bindFramebuffer(GlFramebuffer.java:35)
	at com.mojang.blaze3d.platform.GlStateManager._glBindFramebuffer(GlStateManager.java:1079)
	at net.minecraft.class_276.method_29329(class_276.java:99)
	at net.minecraft.class_761.method_22710(class_761.java:1270)
	at net.minecraft.class_757.method_3188(class_757.java:1110)

-- Affected level --
Details:
	All players: 1 total; [class_746['Impulse_03'/243, l='ClientLevel', x=1.50, y=105.00, z=-5.50]]
	Chunk stats: 961, 447
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,105,0), Section: (at 0,9,0 in 0,6,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 15 game time, 15 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:458)
	at net.minecraft.class_310.method_1587(class_310.java:2406)
	at net.minecraft.class_310.method_1514(class_310.java:826)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2198666584 bytes (2096 MiB) / 3087007744 bytes (2944 MiB) up to 10502537216 bytes (10016 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 3
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 2060
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1f03
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3699
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.00
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 3.00
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 24445.18
	Virtual memory used (MB): 12382.33
	Swap memory total (MB): 8192.00
	Swap memory used (MB): 0.00
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx10000M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Launched Version: Fabric 1.20.1
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: Unknown
	Window size: 1920x1009
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: <disabled>
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fabulous
	Resource Packs: 
	Current Language: ru_ru
	CPU: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Server Running: true
	Player Count: 1 / 8; [class_3222['Impulse_03'/243, l='ServerLevel[Новый мир]', x=1.50, y=105.00, z=-5.50]]
	Data Packs: vanilla
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable

**Comment by CodeKid0** [comment] 2023-08-20 14:48
> Minecraft Version: 1.20.1
This mod was not yet ported for this version of the game

**Comment by thr3343** [comment] 2023-08-25 17:34
AFAIK this tends to happen when the official Mojang launcher is used and fabulous graphics are enabled.
I would try either disabling fabulous graphics or failing that using a 3rd party launcher such as MultiMC or its various forks such as Prism launcher.

**Comment by xCollateral** [comment] 2024-09-16 10:05
If it was caused by fabulous graphics, it should be fixed.

**Closed as completed by xCollateral** 2024-09-16 10:05 UTC

**Comment by Kittyskj** [comment] 2024-09-16 15:14
1 year...

**Comment by xCollateral** [comment] 2024-09-16 15:53
Sorry for the late reply, but consider we have to work on multiple aspect and we have limited time. Having the issue tracker flooded of support requests, duplicated issues does not help.
