### ISSUE TITLE
Crash on Ubuntu Linux

### ISSUE THREAD

**Issue by JhonnyRice** [xCollateral/VulkanMod#101] opened 2022-08-29 13:42 UTC
This mod is incredible, but unfortunately it crashes on my  system.

Error:

```
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_338 failed
```
Here's my config:

Minecraft Version: 1.19.0
Fabric loader Version: 0.14.8
Fabric API Version: fabric-api-0.56.0+1.19
Distro: Ubuntu 21.04
Kernel: Linux 5.15.0-46-generic
CPU: Intel Core i9 10900
GPU: AMD Radeon RX 570 (8Gb edition)
Kernel driver in use (from `lspci`): amdgpu
Java Version: java 17.0.1 2021-10-19 LTS
Vulkan Instance Version (from `vulkaninfo`): 1.3.204

`glxinfo | grep -i vendor` output: 
```
server glx vendor string: SGI
client glx vendor string: Mesa Project and SGI
    Vendor: AMD (0x1002)
OpenGL vendor string: AMD
```

`lspci -k | grep -EA3 'VGA|3D|Display'` output:
```
01:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] (rev ef)
	Subsystem: ASUSTeK Computer Inc. Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
```

Hope this helps. If you need any information just let me know.

**Comment by xCollateral** [comment] 2022-09-01 09:59
I'll close this since it has been solved. The crash was caused by version mismatch and mesa drivers.

**Closed by xCollateral** 2022-09-01 09:59 UTC

**Comment by JhonnyRice** [comment] 2022-09-04 16:25
yeah, but on the other part, these were the lastest mesa drivers i could get.
