### ISSUE TITLE
Glowing effect bug

### ISSUE THREAD

**Issue by XuanXue2008** [xCollateral/VulkanMod#411] opened 2024-05-03 05:54 UTC
![image](https://github.com/xCollateral/VulkanMod/assets/138149926/afd6dc56-5736-46cc-990d-ac6ea7032194)

**Comment by NXTler** [comment] 2024-05-03 11:56
What is the issue? Could you translate it?

**Comment by XuanXue2008** [comment] 2024-05-03 12:18
Too many entities causing rendering errors.
In the case of too many entities, rendering errors occur, resulting in this situation.
I'm poor in English ,so I use the machine translation. :(

**Comment by NXTler** [comment] 2024-05-03 13:10
No problem, the translation turned out just fine. Thanks for reporting this! This error could also be caused by the glowing effect. Could you try to replicate this issue without glowing entities?

**Comment by XuanXue2008** [comment] 2024-05-03 13:49
okay,i will try.
please wait for a moment. : )

**Comment by XuanXue2008** [comment] 2024-05-03 14:19
hey I  have tired again. I used the copy carpet machine to make a lot of entities.It seems that this problem is not caused by the entities.

**Comment by XuanXue2008** [comment] 2024-05-03 14:20
It could cause by the Beacon lights.

**Comment by Enderteck** [comment] 2024-05-04 16:32
Looks to be the same issue that I got

https://github.com/xCollateral/VulkanMod/issues/410

**Comment by XuanXue2008** [comment] 2024-05-04 17:29
Do you have some way to slove this problem?

**Comment by XuanXue2008** [comment] 2024-05-04 17:32
:(
I think mojang should do some work on vulkan.

**Comment by thr3343** [comment] 2024-05-04 17:47
Does this bug occur in 0.4.1?
At least to my current knowledge, this should have been fixed in 0.4.0.

**Comment by XuanXue2008** [comment] 2024-05-04 18:29
yes,I use the latest version.

**Comment by XuanXue2008** [comment] 2024-05-05 01:32
It caused by theglowing effect.
sorry, I made a mistake.   :(   😭

**Comment by XuanXue2008** [comment] 2024-05-05 03:30
![image](https://github.com/xCollateral/VulkanMod/assets/138149926/cd3173d7-79f7-43f4-9fe3-e485b409fd50)

**Closed as completed** 2024-05-06 14:59 UTC
